#' System file helper for the ggwizard package
#'
#' Equivalent to `system.file(..., package = "ggwizard")`.
#' Generated by golem and kept here so it works both in development
#' (devtools::load_all) and when the package is installed.
#'
#' @noRd
app_sys <- function(...) {
  system.file(..., package = "ggwizard")
}
